src/App.css

aligned form Vertically to make button visibile  https://github.com/abhijeet141/CropForesight/issues/3  GSSOC 2023
Before 
After

aligned form Vertically  -GSSOC 2023

---

src/App.css

added blur and glass effect and also adjusted the height and width of from

added glass effect to form

---

src/components/contact.js

I have added a modal that will get displayed when a user successfully submits the Contact Us form
this is the pull request of the issue: https://github.com/abhijeet141/CropForesight/issues/48

Added a success modal on successfully submitting the contact us form

---

src/components/Home.css
src/components/nav.css

Made the page responsive  for every screen and solved the ui breaking issue  and made the page user friendly

responsive home page

---

src/components/404.js

This is the implementation of the navbar in the 404 page of the Cropforesight project of the issue: https://github.com/abhijeet141/CropForesight/issues/49

added navbar in 404 page

---

package-lock.json
package.json
src/components/Weather/Weather.css
src/components/Weather/Weather.jsx

I have added the file Which contains all the things, place it where you want it to be. I have installed Axios Package as it was needed
closes #40

Added Weather Working Page

---

src/components/Home.js
src/components/nav.css

- fixed the abnormal space between logo and other items
Thank You !

Fix: Navbar items alignment

---

src/components/contact.js
src/components/formInput.css

Error message showing below of each fields when input field is blank
Email validation add
If any error occurs on particular field that field can be shown by red border to indicate something happens wrong on that field
@abhijeet141 Check it issue#38 resolved!!

Add JS validation on Contact form issue#38 resolved

---

src/components/Home.css

This PR addresses the issue of flickering in the typography box on the website. The flickering was caused by inconsistent rendering of the typography styles during page load. This PR introduces a solution that ensures a smooth and consistent display of the typography box.
- Identified the root cause of the flickering issue, which was related to the asynchronous loading of the typography CSS file.
- Implemented a preloading mechanism for the typography CSS file to ensure it is fully loaded before the page is rendered.
- Updated the order of CSS file loading to prioritize the typography file.
- Optimized the rendering of the typography styles to reduce the chance of flickering during page load.
- Performed thorough testing on different browsers and devices to verify the fix.
- Created a set …

Fixed Flickering of Typography Box

---

package-lock.json
package.json
src/App.js
src/GoToTop/GoToTop.css
src/GoToTop/GoToTop.jsx
src/components/about.css

Resolved Issue https://github.com/abhijeet141/CropForesight/issues/67
Preview:
https://github.com/abhijeet141/CropForesight-FrontEnd/assets/105661636/0831bab6-5df6-4d94-b2d1-123fd46474a2

Added Scroll to top button

---

package-lock.json
package.json
src/components/Review.js
src/components/about.css
src/components/about.js
src/components/data.js

This is issue is assigned to me to show a testimonial section of the website so here I am doing the PR for the same. Here I attached some screenshots of the section:

Added Testimonials

---

src/App.css
src/components/about.css
src/components/contact.css
src/components/contact.js

Made the Contact page responsive , Solution to issue #69  ( GSSOC23 ) 
|      Original       |       Updated        |
| :-----------------: | :------------------: |
| [Original screenshot](https://drive.google.com/file/d/1RaXxdOa6UULJVxAtS_Oz-j9-TeELGYgh/view?usp=sharing) | [Updated screenshot](https://drive.google.com/file/d/1qIZVMfWcoZ0xs-z-xcBeriN6bKMZHkAf/view?usp=sharing) |

Responsive ContactUs

---

package-lock.json
src/components/404.js
src/components/Home.js
src/components/Weather.js
src/components/about.js
src/components/contact.js
src/components/nav.jsx

Resolved Issue https://github.com/abhijeet141/CropForesight/issues/88#event-9551711147.
Added nav.jsx  .

Resolved Issue #88 , Added nav.jsx

---

package-lock.json
src/components/404.css
src/components/404.js
src/components/Weather.css
src/components/Weather.js
src/components/contact.css

made both contact page and weather page responsive also improved the ui of the contact page
this solves the issue #52

made the contact page and weather page responsive for mobile devices

---

src/App.css
src/components/Weather.css
src/components/Weather.js
src/components/Weather/Weather.jsx

The weather page has been modified.
-Spelling mistake is rectified.
-UI made more attractive while matching the theme of the website.

Weather page modified

---

src/App.css
src/components/Weather.css
src/components/Weather.js
src/components/Weather/Weather.jsx

Reverts abhijeet141/CropForesight-FrontEnd#111

Revert "Weather page modified"

---

public/index.html
public/preloading.css
src/App.js
src/components/faq/faq.jsx

Issue solved: #119 
@abhijeet141 Hey, here is a demo you can check below
https://github.com/abhijeet141/CropForesight-FrontEnd/assets/94003231/c4bef9dc-8931-4b7f-8411-d84144f28dee

Add Preloading Feature

---

src/App.css

##Description
Style was added to the scrollbar, it will improve the UI  of the website.
#136
##Screeshot
https://github.com/abhijeet141/CropForesight-FrontEnd/assets/83147410/6d465c33-eafb-4edf-8e59-a6313a9ad330

 Added style to the scrollbar

---

src/components/Weather.js

I have addressed issues https://github.com/abhijeet141/CropForesight/issues/99 and https://github.com/abhijeet141/CropForesight/issues/98 in the CropForesight repository. In response to user inputting incorrect details, I have implemented an error message feature to provide feedback. Additionally, I have converted the units from Kelvin to Celsius and incorporated the Celsius symbol for a more intuitive user experience. Furthermore, I have fixed a typo in the placeholder text to improve clarity. Please review and validate the changes made.

Weather units, error message and typos

---

package-lock.json
public/index.html
src/App.js
src/components/Loading.js

Added lazy loading feature to the components of the website.

Implemented lazy loading

---

package-lock.json
src/components/Weather.css
src/components/Weather.js

I had made weather section completely responsive and also solved the UI bug. Issue #124 is solved.

I had solved the issue of mobile responsiveness of weather section.

---

src/components/about.css
src/components/about.js

Hello @abhijeet141 ,
Here is a fixed About Section, which contains proper alignment and emoji as per the title and the codebase.
will improve more later on. 
- Added - Details Dection
[Screencast from 28-06-23 04:17:01 AM IST.webm](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/121503426/15e05b86-156a-428e-a115-d51a8d2fc073)

Fixed About Section

---

README.md

The updated readme shall help new comers easily navigate with setting up the project and making their first pull request.
clears issue : #140

Update README.md to make it more comprehensive

---

package-lock.json
src/App.css
src/App.js

Add empty validation on a form to prevent blank data to submit.
After entered all data pop up alert will be shown.
After submit data form data clear.
@abhijeet141 issue#135 resolved!!

Validation add & label colour changed

---

public/index.html

Added meta tags like language, author, open graph, twitter tags, etc.

Meta tags updated

---

package-lock.json
src/App.js
src/components/ExampleOfCrop/CropData.js
src/components/ExampleOfCrop/ExampleCrop.css
src/components/ExampleOfCrop/ExampleCrop.jsx
src/components/nav.jsx

Issue-#97 
Closes: #97 
@abhijeet141 do check it out !
You can click on Example option present in navbar----
I have added -
1.ExampleOfCrop (folder)
-----     1.1. ExampleCrop.jsx
-----      1.2.ExampleCrop.css
-----      1.3.CropData.js ( JSON file)
2.I have added some static data in *JSON* file
3. That data is fetched in *JSX* file
4. I have also added *Search-Engine* so that it will be easier for user to search there respective season.
5. some hover effect to image
Screen Shots:

Added crop found in particular season page  issue-97

---

package-lock.json
src/components/Weather.css
src/components/about.css
src/components/about.js
src/components/contact.css
src/components/contact.js
src/components/faq/faq.css

I've added the same font styles to all the headings and the content, fixed the irregular fonts and styles.

Fixed the font styles

---

src/components/about.js

Adde the Autoo rotation to images in the about us section 
issue #155 
https://github.com/abhijeet141/CropForesight-FrontEnd/assets/103810119/0ce083e6-431e-477d-b8d6-d890b486752d

Added the Auto rotation to images in about us section

---

src/App.css

Enhanced the scrollbar, now the color matches the theme and it looks better :)

Enhanced the scrollbar

---

src/components/Contributor.js
src/components/contributor.css
src/index.css

clears #104 
Please consider this pr, made it weeks ago and better, subset of pr  #183 
https://www.awesomescreenshot.com/video/18898730?key=8256434998b1877eae5fe0b70c39112b

contributors page

---

src/components/Review.css
src/components/Review.js
src/components/about.css
src/components/about.js
src/components/nav.css

solves #171 
UI fixes
responsiveness

Add responsiveness on about page and UI improvement

---

src/components/about.css

#198 About page card
Closes #198 
In about page I'm make card by giving box shadow and also apply hover effect to card.

Design card and hover effect

---

src/components/faq/faq.css

I have done the required changes.
Closes #202 
Please review this. @abhijeet141

Responsiveness for faq 

---

src/components/contributor.css

I just solved some problems 
1. reduce the height of the card
2. add a background color to the card so that we can differentiate it 
If there is any kind of problem and you want to change or remove any feature please, let me know
BEFORE
AFTER

Fix : #246

---

src/App.js

Error Handle properly and resolved issue #248

---

src/components/Weather.css
src/components/Weather.js
src/components/WeatherCard.jsx
src/components/weatherCard.css

- add a new weather card which displays weather for the weather page.
- also, removed overlapping background from the weather page.
previously:
now:
- Created new weather card component for the feature added.
- added styles according to the overall theme and color of the website.

feat: Add weather card

---

src/components/contact.js

Added aria attributes like role, aria-label, aria-describedby to all form components of the contact us form

Added aria attributes to contact us form

---

src/components/Loading.js

Add the logo image and correct the format

fix:  #1043

---

.github/auto-comments.yml

Issue reference = #251 
I have created a Workflow that automatically commits when an issue is opened, a pull request is created, an issue is closed, or an issue is assigned or unassigned.
Enable following Permission

Auto-comments feature is added

---

src/components/Contributor.js
src/components/ExampleOfCrop/ExampleCrop.css
src/components/ExampleOfCrop/ExampleCrop.jsx
src/components/Home.css
src/components/Weather.css
src/components/contributor.css
src/components/faq/faq.css

- Made all the headings uniform in size, style and position
- Improved UI of example page
Resolved issue #208

Fixed varied fonts of headings

---

src/components/ExampleOfCrop/ExampleCrop.css

Fixes issue #253
- Active state
The new Navbar is more responsive , better themed then the previous one .

Search bar UI improved  #253

---

src/components/ExampleOfCrop/ExampleCrop.jsx

Fixes : #290 
Added the search crop feature that allows you to search crops by name.

Adding Search Crop Feature

---

code_of_conduct.md

Fixed #321 I have added the code_of_conduct.md kindly merge the PR @abhijeet141 . Thank you !

Added code_of_conduct.md file to repository

---

src/App.css
src/App.js
src/components/Contributor.js
src/components/ExampleOfCrop/ExampleCrop.jsx
src/components/Form.css
src/components/Form.js
src/components/Home.css
src/components/Home.js
src/components/Login.js
src/components/Review.js
src/components/Weather.js
src/components/Weather/Weather.jsx
src/components/about.css
src/components/about.js
src/components/contact.css
src/components/contact.js
src/components/faq/faq.jsx
src/components/nav.css
src/components/nav.jsx
src/index.css

Fixes issue :  #254 
@abhijeet141 , this is a new branch so i had to create a new pr . the older one now have very large number of conflicts due to major changes in the codebase

Implemented Fresh Dark mode on each page #254

---

src/App.css
src/components/Weather.css
src/components/nav.css
src/components/weatherCard.css

Fixed hamburger issue #280 
Before:
After Fixed the issue:
[screencast-practice.geeksforgeeks.org-2023.08.07-17_21_09.webm](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/106610322/3f2c2f79-9273-401c-94c8-7d37bf5dc5f0)

Fixed hamburger issue 

---

src/App.css
src/components/Weather.css

Fixed Form Responsive issue #279 
Before:
After Fixing the issue it now looks like this:
[screencast-practice.geeksforgeeks.org-2023.08.07-17_19_16.webm](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/106610322/a1e99ba1-abda-432a-8038-b15e1273dbcb)

Fixed Form Responsive issue

---

src/components/Form.css
src/components/Form.js

Login page is not responsive

---

src/components/contributor.css

old:
new:
https://github.com/abhijeet141/CropForesight-FrontEnd/assets/103810119/9916579d-b17e-44cd-9c26-d704eea162c2

Remove gap in Contributors card

---

src/components/contact.css

This is a dummy PR in reference to PR #230 , as you asked for creating dummy PR , i just removed comments from css now please check it and merge it if possible

removed css warning in contact

---

src/App.js
src/components/Form.js
src/components/Register.css
src/components/Register.js

solves #327 
@abhijeet141 Hey, I added the register. It's responsive and also has the option to go login page

Adding Register Page

---

package-lock.json
package.json
src/components/Footer.css
src/components/Footer.js
src/index.js

https://github.com/abhijeet141/CropForesight-FrontEnd/assets/103810119/33c7659b-754a-4833-90e8-03429b9778f1

Adding footer

---

src/components/ExampleOfCrop/ExampleCrop.css
src/components/ExampleOfCrop/ExampleCrop.jsx
src/components/nav.css

fixed #229 
closes #229 
Earlier
now
@abhijeet141 please review my PR

removed background from search input

---

src/components/Review/Review.css
src/components/Review/Review.js

Before:
After:
https://github.com/abhijeet141/CropForesight-FrontEnd/assets/103810119/8832e95c-0123-42e7-9ddc-47f7e8c6e17a

Improved testimonials section

---

src/components/About/about.css
src/components/Home/Home.css
src/components/Home/Home.js

fixes #361 
close #361 
In this PR I'm removing border of title in card and also add padding to home page card.

remove border

---

src/App.js
src/components/ForgotPassword/ForgotPassword.css
src/components/ForgotPassword/FotgotPassword.js
src/components/Form.js

solves #328 
@abhijeet141 Done
In forgot page navbar is not needed that's why I not added it

Add forgot password page

---

src/components/404page/404.css
src/components/Contact/contact.css

Fixed Contact Page Responsive issue #346 
[screencast-crop-foresight-front-e9n6l8uyq-abhijeet141.vercel.app-2023.08.09-18_40_50.webm](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/106610322/a43dfdba-b834-48da-9ae1-088692898d37)

Solved Contact Page Responsive Issue

---

src/components/Contributors/Contributor.js
src/components/Contributors/contributor.css

Fixes issue #285 
https://github.com/abhijeet141/CropForesight-FrontEnd/assets/95973644/cb5fdd51-327f-4b2c-861a-f05f00da43c7

redid the contributor page design

---

package-lock.json
package.json
src/App.js
src/components/Form.css
src/components/Form.js
src/components/Profile/Profile.js
src/components/Profile/style.css
src/components/Register/Register.js
src/components/nav.jsx
src/firebase-config.js

Add user profile page

---

package-lock.json
package.json
src/components/Form.js
src/components/Register/Register.js
src/firebase-config.js

Add firebase authentication

---

.github/workflows/greeting.yml

Fixes issue #286 
Added workflow to greet the user when they open an issue or make a new pr

added github worflow for greeting

---

src/components/Footer.css
src/components/Home/Home.js
src/components/Weather.js
src/index.js

Fixes #376 
close #376 
In this PR I'm fixes the position of footer .

footer in weather page

---

src/components/nav.jsx

FIX: #395 
1. highlighting the selected page in navbar
2. use of uselocation hook by react-router-dom
3. comment if you want a change in highlighted color

highlighted selected page in navbar
